# This is an example OpenEMPIRE configuration file. 
# To be used with the execution script OpenEMPIRE/run.py

USE_TEMP_DIR : False #
temp_dir : './'
version : 'bolivia_v1'
Horizon : 2040
NoOfScenarios : 1
lengthRegSeason : 168
discountrate : 0.07
WACC : 0.05
solver : "Gurobi" # "Gurobi"  # #"CPLEX" #"Xpress"
scenariogeneration : True #False
fix_sample : False #True
LOADCHANGEMODULE : False #True
filter_make : False #True #
filter_use : False #True #
n_cluster : 10
moment_matching : False #True
n_tree_compare : 20
EMISSION_CAP : True #False
IAMC_PRINT : False #True
WRITE_LP : False #True
PICKLE_INSTANCE : False #True 
